[package]
name = "statusline-jelford"
version = "0.1.0"
authors = ["James Elford <james.p.elford@gmail.com>"]
edition = "2018"

[profile.release]
lto = true

[dependencies]
chrono = "0.4"
getopts = "0.2"
